/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class win_dutoe_IceAnalysis */

#ifndef _Included_win_dutoe_IceAnalysis
#define _Included_win_dutoe_IceAnalysis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     win_dutoe_IceAnalysis
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_win_dutoe_IceAnalysis_helloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
