/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class win_dutoe_IceAnalysis */

#ifndef _Included_win_dutoe_IceAnalysis
#define _Included_win_dutoe_IceAnalysis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     win_dutoe_IceAnalysis
 * Method:    libIceAnalysis
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_win_dutoe_IceAnalysis_libIceAnalysis
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
